### ISSUE TITLE
 PAL crashing when setting subtitles to OFF

### ISSUE THREAD

**Issue by dekaidekai** [JourneyDocker/Plex-Auto-Languages#1]
If you set an episode's subtitles to `off`, I believe it crashes:
```
Traceback (most recent call last):
  File "/app/plex_auto_languages/plex_alert_handler.py", line 66, in _process_alerts
    alert.process(self._plex)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/app/plex_auto_languages/alerts/playing.py", line 85, in process
    plex.change_tracks(username, item, EventType.PLAY_OR_ACTIVITY)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plex_auto_languages/plex_server.py", line 256, in change_tracks
    track_changes.compute(episodes)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/app/plex_auto_languages/track_changes.py", line 85, in compute
    matching_subtitle_stream = self._match_subtitle_stream(part.subtitleStreams())
  File "/app/plex_auto_languages/track_changes.py", line 208, in _match_subtitle_stream
    if self._subtitle_stream.forced == stream.forced:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'forced'
```

I think because it is expected [here](https://github.com/RemiRigal/Plex-Auto-Languages/blob/d08a88aed67329f4388309a5c88ab55433fd5fb4/plex_auto_languages/track_changes.py#L181) that `self._subtitle_stream`, which is the currently selected subtitle stream, to be not `None`, but it is if we set the subtitles to be off.

We need to find a way to handle when subtitles are turned off, and set all future episodes to turn off subtitles.

**Comment by dekaidekai** [comment]
@JourneyDocker You are right, I tried on another show and turning it OFF worked correctly without crashing. But the first show I did if I set to OFF will show this crash. So it might be depending on the show 🤔

**Comment by JourneyOver** [comment]
as noted previously before we moved the issue over here I haven't experienced this issue myself any, but I'm wondering if the simple fix for this would just be to change:

```
        scores = [0] * len(streams)
        for index, stream in enumerate(streams):
            if self._subtitle_stream.forced == stream.forced:
                scores[index] += 3
            if self._subtitle_stream.hearingImpaired == stream.hearingImpaired:  # Add score for SDH subtitles
                scores[index] += 3
            if self._subtitle_stream.codec is not None and stream.codec is not None and \
                    self._subtitle_stream.codec == stream.codec:
                scores[index] += 1
            if self._subtitle_stream.title is not None and stream.title is not None and \
                    self._subtitle_stream.title == stream.title:
                scores[index] += 5
```

to:
```
    scores = [0] * len(streams)
    for index, stream in enumerate(streams):
        if self._subtitle_stream and self._subtitle_stream.forced == stream.forced:
            scores[index] += 3
        if self._subtitle_stream and self._subtitle_stream.hearingImpaired == stream.hearingImpaired:
            scores[index] += 3
        if self._subtitle_stream and self._subtitle_stream.codec is not None and stream.codec is not None and \
                self._subtitle_stream.codec == stream.codec:
            scores[index] += 1
        if self._subtitle_stream and self._subtitle_stream.title is not None and stream.title is not None and \
                self._subtitle_stream.title == stream.title:
            scores[index] += 5
```

Specifically adding a `self._subtitle_stream` to each one.

**Comment by dekaidekai** [comment]
@JourneyOver I think this could prevent the crash 👍  
But I'll need to test if that would still not set the rest of the episodes to `OFF`.

**Comment by dekaidekai** [comment]
I have two shows, one that works and one that doesn't, so I think I can fool around on the code and make a fix for this!

**Comment by JourneyOver** [comment]
Sounds good! \^^ I also moved the other issue (the SDH one) over as well so hopefully we can knock both of them out.

**Comment by JourneyOver** [comment]
So I can at least confirm the above solution that I was thinking of will not work at least, it did exactly as you thought it probably would xD

**Comment by dekaidekai** [comment]
Actually this latest commit for this [issue](https://github.com/JourneyDocker/Plex-Auto-Languages/issues/2#issuecomment-2561970770) fixed it and I don't experience the crash anymore!

But I still see if I set the subtitles to off, while the episode sets the current episode playing to off, PAL sets all the episodes in the show to be forced subtitles instead if they are available.

I'm guessing again because this is because PALs default behaviour is that it no subtitles is selected, it automatically sets it to any forced subtitle available [here](https://github.com/JourneyDocker/Plex-Auto-Languages/blob/17972923100b195617a169bcf514db16dc5ced6e/plex_auto_languages/track_changes.py#L184).

**Comment by JourneyOver** [comment]
Hmm I'm wondering if we just turn the value from True to False if it would stop the forced subtitle thing for the time being until we can come up with a more concrete plan on how we want things done by default, maybe we could add a config/env option to configure it between true/false value as well?

**Comment by dekaidekai** [comment]
@JourneyOver I think actually I am honestly fine in leaving it for now, but up to you!

I understand the incentive behind PAL setting it to `forced` if nothing is set, because usually people who watch a show who don't want any subtitles on will at least want some subtitles for the foreign parts, which is what `forced` is for. So PAL is assuming that when setting it as the backup subtitles.

But I also think in the future it would be nice to consider if there is a case when a user wants to set subtitles to `off` completely. Essentially it's the users responsibility and own decision saying "I understand even if this show has foreign parts that may offer forced subtitles for it, I want all subtitles off and PAL to set that".

**Comment by JourneyOver** [comment]
Alright, yea def understand the point you are getting at, I always end up enabling subtitles of some kind anyways if I know a show has a lot of foreign parts to it so I may just leave things how they are then for now and if in the future someone chimes in that they want things changed or whatever then I might make the thing into an optional choice.

Either way are we calling this (the crashing) issue fixed then as well? since you mentioned above the latest commit seems to have fixed the crash you was experiencing before.

**Comment by dekaidekai** [comment]
Yeah these are both fine I think closing them 🙏 

Thanks again!

**Comment by JourneyOver** [comment]
Sounds great! I'll get a new `latest` tag pushed up here very shortly then as well.

It's not a problem :P
