### ISSUE TITLE
PAL can't differentiate SDH and regular subtitle

### ISSUE THREAD

**Issue by JourneyOver** [JourneyDocker/Plex-Auto-Languages#2]
Original Comment:
> i have a show where there are 2 english subs: _English_ and _English SDH_. When i select _English_, PAL sets _English SDH_ for the whole show.
> 
> Here is what the XML contains:
> 
> ```
> <Stream id="119071" streamType="3" canAutoSync="0" codec="srt" index="11" bitrate="0" language="English" languageTag="en" languageCode="eng" hearingImpaired="1" title="SDH" displayTitle="English SDH" extendedDisplayTitle="SDH (English SRT)"></Stream>
> <Stream id="119072" streamType="3" canAutoSync="0" selected="1" codec="srt" index="12" bitrate="0" language="English" languageTag="en" languageCode="eng" displayTitle="English" extendedDisplayTitle="English (SRT)"></Stream>
> ```
> 
> It seems one has `hearingImpaired="1"`, which should be sufficient for PAL to use the other one, and not only match on `languageTag`.

### This above part seems to be fixed

---------------------------------------------------------------------------

Follow ups from https://github.com/RemiRigal/Plex-Auto-Languages/issues/106

Current issue: It's automatically forcing `SDH` subtitles, like how it does for `Forced` Subtitles on scanning anything and does not allow user to set subtitles back to off as upon setting to off, it ends up forcing the SDH subtitle back on shortly after.

This seems to only be specifically happening when the only options are either `Off` or the `SDH` subtitle, if there are multiple subtitles it does not automatically set the subtitle to `SDH`

// CC @dekaidekai 

I'm moving this issue over here as well.

**Comment by dekaidekai** [comment]
@JourneyOver I'll test around on a tv show with only SDH subtitles and get back to you!

**Comment by JourneyOver** [comment]
Sounds good! hopefully you can reproduce what I'm experiencing and see if you are able to fix it or not, as some things I have tried myself sadly did not work >.<

**Comment by JourneyOver** [comment]
To add more testing into this: 

Setting `update_strategy` to `next` instead of `all` and going in and switching the subtitle from an `SDH` to `off` leaves said subtitle `off` for that specific episode unless (unless you go back to a previous episode that had a subtitle set) but it doesn't seem to change any other subtitles for any of the episodes that follow nor any of the following seasons that follow.

**Comment by dekaidekai** [comment]
@JourneyOver Okay thanks for the note, also do you know what your settings in Plex are for subtitles preferences? I haven't looked that far in the code if that affects PAL, but want to make sure if that affects anything, that our environments are the same.

**Comment by JourneyOver** [comment]
These are my subtitle settings in plex:
![image](https://github.com/user-attachments/assets/ddaf25c7-92a0-4d22-92e2-ef7a85db5db0)

**Comment by dekaidekai** [comment]
@JourneyOver Do you see these bottom settings under your Account settings? I assume you don't have SDH preferred searches on?

<img width="978" alt="Screenshot 2024-12-24 at 10 13 19 PM" src="https://github.com/user-attachments/assets/d34e6ac8-1f6b-48d1-bee9-da2e55de92c3" />

**Comment by JourneyOver** [comment]
ooops lol these are my settings for account:
![image](https://github.com/user-attachments/assets/45c7bf9c-40ff-42ab-9af7-26d16193b072)


the previous ones was for the server xD

**Comment by JourneyOver** [comment]
I'm wondering if since we are at this as well if we should make `forced` subs just user choice as well instead of forcing it to automatically be selected, but idk.

**Comment by dekaidekai** [comment]
@JourneyOver Yeah good idea 🤔 
Just a little progress, I think this new issue it might be due to this block [here](https://github.com/JourneyDocker/Plex-Auto-Languages/blob/9028c2ee904ce68de97fef1dd1aa5c5aede5443f/plex_auto_languages/track_changes.py#L195). As it returns the first subtitles regardless of what is if it's the only one.

Where in the old [code](https://github.com/JourneyDocker/Plex-Auto-Languages/blob/08ffb37a92e41f98b4ed092e0fca586247e7220f/plex_auto_languages/track_changes.py#L191), we always filtered to to forced subtitles only.

**Comment by JourneyOver** [comment]
@dekaidekai hmm lemme try switching some lines around a tiny bit and see if that makes any difference or not. Will report back in a couple minutes or so.

**Comment by dekaidekai** [comment]
Yep switching it around so forced check is first would fix it 👍 

But this does really open a bigger question on why does PAL pick forced subtitles first if nothing is picked yet. As you said should that be configurable, etc.

**Comment by dekaidekai** [comment]
I'm signing off for the night but I'll be on later this week to look around in the code.

Thanks again for everything! Happy holidays! 🎄

**Comment by JourneyOver** [comment]
Yep can confirm as well ^^ and yep lol we should probably look into that soon enough. and it's not a problem! Glad to be of help and all that when I can and ofc make fixes (even if said fixes come from other people xD) for something that was abandoned by someone else.  Happy holidays to you as well :)

**Comment by dekaidekai** [comment]
Yeah the latest commit on main works for me now! A show with just SDH defaults to off now for me 👍

**Comment by JourneyOver** [comment]
Great! So that just leaves #1 left then to fix up and then I'll make a new release. Going to go ahead and close this issue on up.
